### PR TITLE
Fix/styling

### PR DESCRIPTION
**Pull request by EricBartusch**

### CODE REVIEW

**Comment by ErikElkins** [comment]
Do you mind if i pull this down and refactor some pieces? That'll probably be easier than trying to communicate though the PR.

**Comment by EricBartusch** [comment]
Yeah, are you wanting to try to build it too?  How do you plan on validating you didn't break stuff?

**Comment by ErikElkins** [comment]
Yeah I should probably get it going on my local machine

**Comment by EricBartusch** [comment]
It's rough, I can help you through it tomorrow.

**Comment by ErikElkins** [comment]
The rest looks good by my eye. Feel free to review what I added.

**Review by ErikElkins — APPROVED** [review]

**Pull request merged**
